workflows:
  ios-workflow:
    name: iOS Compose Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      # Обязательно для Kotlin Multiplatform
      java: 17
      xcode: latest
    scripts:
      - name: Build Unsigned IPA
        script: |
          # Останавливаем скрипт сразу, если хоть одна команда выдаст ошибку
          set -e 
          
          echo "Даем права на запуск Gradle..."
          chmod +x ./gradlew
          
          echo "Переходим в папку iOS проекта..."
          cd iosApp
          
          echo "Начинаем сборку через xcodebuild..."
          xcodebuild build \
            -project "iosApp.xcodeproj" \
            -scheme "iosApp" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            -derivedDataPath ./build-data

          echo "Упаковываем приложение..."
          mkdir -p Payload
          cp -R ./build-data/Build/Products/Release-iphoneos/iosApp.app Payload/
          zip -qr ../olcbox_client.ipa Payload
          
          echo "Готово!"
    artifacts:
      - "*.ipa"
